language: java
sudo: required
jdk:
  - openjdk11
cache:  
  directories:  
   - $HOME/.m2  
services:
  - xvfb
# Enable UI
before_install:
    - sh -e /etc/init.d/xvfb start - sleep 10
    - git clone --depth 1 https://github.com/kit-sdq/BuildUtilities.git /tmp/BuildUtilities
    - . /tmp/BuildUtilities/travis-ci/setupenvironment.sh
install: true

script: mvn clean verify
