package tools.vitruv.applications.automationml.colladachanges

import mir.reactions.combinedColladaChanges.CombinedColladaChangesChangePropagationSpecification

class CombinedColladaChangePropagationSpecification extends CombinedColladaChangesChangePropagationSpecification {
	
}