package tools.vitruv.applications.automationml.colladachanges

import mir.reactions.combinedcollada.CombinedcolladaChangePropagationSpecification

class CombinedColladaChangePropagationSpecification extends CombinedcolladaChangePropagationSpecification {
	
}