package tools.vitruv.applications.automationml.aggregatorchanges

import mir.reactions.combinedAggregatorChanges.CombinedAggregatorChangesChangePropagationSpecification

class CombinedAggregatorChangePropagationSpecification extends CombinedAggregatorChangesChangePropagationSpecification {
	
}