package tools.vitruv.applications.automationml.attributechanges

import mir.reactions.combinedAttributeChanges.CombinedAttributeChangesChangePropagationSpecification

class CombinedAttributeChangePropagationSpecification extends CombinedAttributeChangesChangePropagationSpecification {
	
}