package tools.vitruv.applications.plcopencaex.plcopen2caex

import mir.reactions.AbstractChangePropagationSpecificationTc6_0201ToCaex

class PLCOpen2CAEXChangePropagationSpecification extends AbstractChangePropagationSpecificationTc6_0201ToCaex {
	
}