package tools.vitruv.applications.plcopencaex.plcopen2caex

import mir.reactions.plcopen2caex.Plcopen2caexChangePropagationSpecification

class PLCOpen2CAEXChangePropagationSpecification extends Plcopen2caexChangePropagationSpecification {
	
}