package tools.vitruv.applications.automationml.plcopenchanges

import mir.reactions.combinedPLCopenChanges.CombinedPLCopenChangesChangePropagationSpecification

class CombinedPLCopenChangePropagationSpecification extends CombinedPLCopenChangesChangePropagationSpecification {
	
}