package tools.vitruv.applications.automationml.caexchanges

import mir.reactions.combinedCAEXChanges.CombinedCAEXChangesChangePropagationSpecification

class CombinedCAEXChangePropagationSpecification extends CombinedCAEXChangesChangePropagationSpecification {
	
}